### ISSUE TITLE
Can't open the dxf files in AutoCAD

### ISSUE THREAD

**Issue by resuly** [active-programming/DXF-Creator-for-PHP#2]
The generated dxf files from demo1.php and demo2.php are not work in Auto CAD 2016.

**Comment by adamasantares** [comment]
Hi,
that's sad, I used http://help.autodesk.com/view/ACD/2016/ENU/?guid=GUID-235B22E0-A567-4CF6-92D3-38A2306D73F3 docs when writen code. I can download only ACD2017 for testing. I'll check it soon.

**Comment by ioulian** [comment]
Hi,

I'm currently also using this bundle for our project. The issue persists, you can't open .dxf file in Autocad 2016 (I'm testing on OSX).

When opening the file it will say "Press enter to continue", then (without pressing enter) you can press "F2" to show errors.

For the demo file there are 2 errors:

1: the default layer color is 0, but it needs to be between 1-255, so I've changed "const LAYER" to "1" instead of "0" in "Color.php". So this issue is fixed
2: Linetypes (DASHDOT and DASHED) also create a problem. I haven't looked into it yet, but you can use default line style for now.

Now the file should open.

I'll try to fix them when I have time and create a merge request.

**Comment by adamasantares** [comment]
@ioulian 

that's great! You figured out the problem. Just need to fix default color value.

Looks like this value:

```
    /**
     * Default layer's color
     */
    const LAYER = 0;
```

doesn't supports anymore.

**Comment by adamasantares** [comment]
@ioulian 

I changed default color to gray, not sure what color is better as default.

**Comment by t-o-o-m** [comment]
The issue with missing line styles still persists. You can't use any other than the default line style, since AutoCAD misses definitions for any other styles.

**Comment by adamasantares** [comment]
@t-o-o-m 

can you please check last 0.1.4b cersion?
