### ISSUE TITLE
Groupcode 90 Problem with AutoDesk

### ISSUE THREAD

**Issue by seewolf135** [active-programming/DXF-Creator-for-PHP#4]
Hey,
the DXF-Creator is great. It works! With LibreCAD or BricsCAD, but AutoCAD will not open the Drawings. Other programms sayed "Problem with Groupcode 90". There is something wrong with the Polygons. Why do u don't close the Polygon?

Example Polygon [x1, y1, x2, y2, x3, y3, ....xn, yn, ...... x1,y1]

**Comment by adamasantares** [comment]
Hi @seewolf135 ,

could you show the code example? I'll try to fix it.

I'm still using this lib. in one of project :) thanks for feedback.

**Comment by dbaldzhiev** [comment]
This happens when you try to generate polylines. The output of demo2.php cannot be opened with Autocad due to "problem with groupcode 90". The issue roots deeper because the files generated are AC1006 - DWG Release 10. and afaik it does not support LWPOLYLINE.
I do not have solution to the problem as my coding skills are not up to par.

**Comment by adamasantares** [comment]
I've changed it to AC1009...I hope it will help

**Comment by adamasantares** [comment]
@dbaldzhiev 

can you please try last beta version "0.1.4b"? It should work in autocad.
